InsuranceManagement/Controllers/InsuranceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using InsuranceCore.DTO;
using InsuranceCore.Interfaces;
using InsuranceCore.Models;
using InsuranceInfrastructure.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Microsoft.Extensions.Logging;
using static InsuranceCore.DTO.ReusableVariables;
using Microsoft.AspNetCore.StaticFiles;
using InsuranceCore.Enums;
using static InsuranceInfrastructure.Helpers.AccessControlAttribute;
using InsuranceManagement.ViewModels;
using InsuranceInfrastructure.Middlewares;
using System.Text;
using CsvHelper;
using Microsoft.AspNetCore.Http;


namespace InsuranceManagement.Controllers
{
    [TypeFilter(typeof(AuditFilterAttribute))]
    public class InsuranceController : Controller
    {
        //private readonly ILogger<InsuranceController> _logger;
        private readonly IInsuranceService _service;
        private readonly ILoggingService _logging;
        private readonly IRequestService _reqservice;
        private readonly IHttpClientService _httpClientService;
        private IHttpContextAccessor _hcontext;
        TemporaryVariables temporaryVariables;
        //GlobalVariables globalVariables;
        //private readonly GlobalVariables _globalVariables;
        private readonly TemporaryVariables _temporaryVariables;
        private readonly ISessionService _session;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly string generalVariable;


        public InsuranceController(IHttpClientService httpClientService, IHttpContextAccessor hcontext,/* ILogger<InsuranceController> logger,*/
            ISessionService session, IInsuranceService service, ILoggingService logging, IRequestService reqservice, IHttpContextAccessor httpContextAccessor)
        {
            //_logger = logger;
            _logging = logging;
            _service = service;
            _reqservice = reqservice;
            _httpClientService = httpClientService;
            _hcontext = hcontext;
            _session = session;

            //generalVariable = _httpContextAccessor.HttpContext.Session.GetString("GlobalVariables");
            //if (generalVariable != null)
            //{
            //    _globalVariables = JsonConvert.DeserializeObject<GlobalVariables>(generalVariable) ?? new GlobalVariables();
            //}
            //else
            //{
            //    // Handle the case where the JSON string is null
            //    _globalVariables = new GlobalVariables();
            //}           // _globalVariables = _session.Get<GlobalVariables>("GlobalVariables");
            // _temporaryVariables = _session.Get<TemporaryVariables>("TemporaryVariables");
            _httpContextAccessor = httpContextAccessor;
        }
        public GlobalVariables GetGlobalVariables()
        {
            try
            {
                string generalVariable = _httpContextAccessor.HttpContext.Session.GetString("GlobalVariables");

                if (!string.IsNullOrEmpty(generalVariable))
                {
                    return JsonConvert.DeserializeObject<GlobalVariables>(generalVariable) ?? new GlobalVariables();
                }
            }
            catch (Exception ex)
            {

                _logging.LogError(ex.ToString(), "SearchWithParameters");
            }
            return new GlobalVariables();


        }
        public IActionResult Index()
        {
            GlobalVariables _globalVariables = GetGlobalVariables();
            //var session = _httpContextAccessor.HttpContext.Session;
            //session.SetString("GlobalVariables", JsonConvert.SerializeObject(globalVariables));
            //  _session.Set<GlobalVariables>("GlobalVariables", globalVariables);

            return View();
        }
        public async Task<IActionResult> Report()
        {
            GlobalVariables _globalVariables = GetGlobalVariables();

            var reports = await _reqservice.ReportReport();
          //  _logging.LogInformation($"{_globalVariables.name} requested insurance report {JsonConvert.SerializeObject(reports)} ", "Report");

            return View(reports);
        }
        public IActionResult Unauthorized()
        {
            return View();
        }

        [HttpGet]
        public IActionResult FetchAccountDetails()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> FetchAccountDetails(string accountNumber)
        {

            if (accountNumber == null) return null;
            var getaccountdetail = await _service.FetchDetail(accountNumber.Trim());
            //var accountDetail = new AccountDetail
            //{
            //    // Populate properties based on fetched data
            //    AccountName = "Sample Account Name",
            //    CustomerName = "Sample Customer Name",
            //    T24CustomerID = "Sample Customer ID",
            //    CustomerEmail = "sample@example.com"
            //};
            if (getaccountdetail == null) return null;
           // _logging.LogInformation(JsonConvert.SerializeObject(getaccountdetail), "FetchAccountDetails");

            return Json(getaccountdetail);
        }
        //[HttpPost]
        //public async Task<AccountDetail> FetchAccountDetail(string AccountNUmber)
        //{
        //   return  await _service.FetchDetail(AccountNUmber);
        //}
        //[EncryptionActionAttribute]
        //[HttpGet]
        //public IActionResult GetAllInsurance()
        //{
        //   // var getall = await _service.GetAllInsuranceRequest();
        //    return View();
        //    //var response = await _reqservice.FetchInsurancesData();
        //    //return Json(response);
        //}
        //  [AccessControl( "INR", "AUR")]
        [HttpPost]
        public async Task<IActionResult> FetchInsurances(DataTablesRequest request)
        {
            try
            {
                var json = await _reqservice.FetchInsurancesForDataTableAsync(request);
                //var test = JsonConvert.SerializeObject(json);
               //  _logging.LogInformation($"Received JSON data: {JsonConvert.SerializeObject(json.data)}", "FetchInsurances");
                return Json(json);
            }
            catch (Exception ex)
            {
                _logging.LogError(ex.ToString(), "FetchInsurances");
                throw;
            }


        }
        //[HttpPost]
        ////[ValidateAntiForgeryToken]
        //public async Task<IActionResult> FetchInsurancesWithoutCodition()
        //{
        //    try
        //    {
        //        var data = await _reqservice.ProcessInsuranceRequest();

        //        // Create a DataTablesResponse object with the simulated data
        //        var dataResponse = new DataTablesResponse(1, data, data.Count, data.Count);

        //        return Json(dataResponse);
        //    }
        //    catch (Exception ex)
        //    {
        //        _logging.LogError(ex.ToString(), "FetchInsurancesWithoutCodition");
        //        throw;
        //    }


        //}
        public IActionResult GetAllInsurance()
        {
            return View();

        }
        public async Task<IActionResult> AuthorizeRequest(string message = null)
        {
            GlobalVariables _globalVariables = GetGlobalVariables();
            try
            {
                if (!_globalVariables.Permissions.Contains(GetPermissionName(Permissions.AUR))) return RedirectToAction("Unauthorized");
                var getAll = await _reqservice.GetAllNeededforAuth();
                //await _reqservice.GetAllNeeded(r => r.Stage == InsuranceStatus.New.ToString()  &&  r.UserId != _globalVariables.userid);
               // _logging.LogInformation(getAll.Count().ToString(), "AuthorizeRequest");

                if (getAll == null)
                {
                    return RedirectToAction("GetAllInsurance");
                }

                var records = new List<AuthorizeRequestViewModel>();
                var approveRejectList = new List<SelectListItem>
                {
                    new SelectListItem { Text = "Approve", Value = RequestStatus.Approved.ToString() },
                    new SelectListItem { Text = "Reject", Value = RequestStatus.Rejected.ToString() }
                };
                ViewBag.ApproveRejectList = new SelectList(new[]
                {
                    new { Text = "Approve", Value = "Approved" },
                    new { Text = "Reject", Value = "Rejected" }
                }, "Value", "Text");

                // Set it in ViewBag
                //ViewBag.ApproveRejectList = new SelectList(approveRejectList, "Value", "Text");

                foreach (var item in getAll)
                {


                    var record = new AuthorizeRequestViewModel()

                    {
                        RequestId = Convert.ToInt64(item.RequestID),
                        Comment = null,
                        IsApproved = null,
                        T24CustomerID = item.CustomerID,
                        AccountName = item.AccountName,
                        CustomerName = item.CustomerName,
                        CustomerEmail = item.CustomerEmail,
                        AccountNumber = item.AccountNo,
                        EstimatedPremium = item.UpdatedPremium,
                        InsuranceType = item.InsuranceType.Name,/*.Name,*/
                        //InsuranceType = getInsuranceType.Name,
                        InsuranceSubType = item.InsuranceSubType?.Name,
                       /*getInsuranceSubType?.Name ?? null,*/
                      //  Broker = item.Broker.AccountName
                        //,ApprovalStatus = ""
                    };

                    records.Add(record);
                }

InsuranceManagement/Views/Broker/BrokerInsuranceIndex.cshtml
@model IEnumerable<InsuranceCore.Models.BrokerInsuranceType>

@{
    ViewData["Title"] = "BrokerInsuranceIndex";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2 style="text-align: center;">Broker Insurance List</h2>
<div class="container-fluid">
    @{
        if (ViewData["Error"] != null || ViewData["Message"] != null)
        {
            string alertType = ViewData["Error"] != null ? "danger" : "success";
            string alertIcon = ViewData["Error"] != null ? "fa-exclamation-circle" : "fa-check-circle";
            string alertHeading = ViewData["Error"] != null ? "Error!" : "Success!";
            string alertMessage = ViewData["Error"] != null ? ViewData["Error"].ToString() : ViewData["Message"].ToString();
            <div class="alert alert-@alertType alert-dismissible fade show" role="alert" id="dynamic-alert">
                <!-- Add cancel button with icon at the top -->
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="d-flex align-items-center">
                    <i class="fa @alertIcon me-2"></i>
                    <div>
                        <h5 class="alert-heading">@alertHeading</h5>
                        <p id="alert-message">@alertMessage</p>
                    </div>
                </div>
            </div>
        }
    }

</div>
@if (TempData.ContainsKey("ResultMessage"))
{
    <div class="alert @((TempData["ResultMessage"].ToString().StartsWith("Success")) ? "alert-success" : "alert-danger")" id="resultMessage">
        @TempData["ResultMessage"]
    </div>
}
<button type="button" class="btn btn-primary" style="background-color: #25237a;">
    <a asp-action="CreateBrokerInsuranceType" style="color: white; text-decoration: none;">Create New</a>
</button>
<input type="text" id="searchTerm" placeholder="Search by name...">
<table class="table">
    <thead>
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>*@


            <th>
                @Html.DisplayNameFor(model => model.Broker)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InsuranceType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>*@


                <td>
                    @Html.DisplayFor(modelItem => item.Broker.BrokerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InsuranceType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <button type="button" class="btn btn-sm btn-primary" style="background-color: #25237a; display: inline-block;">
                        <a asp-action="EditBrokerInsuranceType" asp-route-id="@item.Id" style="color: white; text-decoration: none;"><i class="zmdi zmdi-edit"></i></a>
                    </button>

                    <button type="button" class="btn btn-sm btn-danger" style="background-color: #f00; border-color: #f00; display: inline-block;">
                        <a asp-action="DeleteBrokerInsuranceType" asp-route-id="@item.Id" style="color: white; text-decoration: none;"><i class="zmdi zmdi-delete"></i></a>
                    </button>
                </td>

            </tr>
        }
    </tbody>
</table>

<script src="~/assets/bundles/libscripts.bundle.js"></script>
@*<script src="~/assets/bundles/mainscripts.bundle.js"></script>*@
<script src="~/assets/bundles/vendorscripts.bundle.js"></script>

<script>
    const searchInput = document.getElementById('searchTerm');

    searchInput.addEventListener('keyup', (e) => {
        if (e.key === "Enter") {
            searchByName();
        }
    });

    function searchByName() {
        const searchTerm = searchInput.value.trim().toLowerCase();
        const rows = document.querySelectorAll('tbody tr');

        rows.forEach(row => {
            const accountNameCell = row.getAttribute('data-account-name').toLowerCase();

            if (!accountNameCell.includes(searchTerm)) {
                row.style.display = 'none';
            } else {
                row.style.display = '';
            }
        });

        // Show "No results" if needed
        showNoResultsMessage();
    }

    function showNoResultsMessage() {
        const visibleRows = document.querySelectorAll('tbody tr:not([style*="display: none"])');

        if (visibleRows.length === 0) {
            // Show no results message or take appropriate action
        } else {
            // Hide no results message or take appropriate action
        }
    }

    // Initially filter on page load
    searchByName();
</script>

InsuranceManagement/Views/Broker/BrokerInsuranceSubTypeIndex.cshtml
@model IEnumerable<InsuranceCore.Models.BrokerSubInsuranceType>

@{
    ViewData["Title"] = "BrokerInsuranceSubTypeIndex";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2 style="text-align: center;">Broker InsuranceSubType List</h2>
<div class="container-fluid">
    @{
        if (ViewData["Error"] != null || ViewData["Message"] != null)
        {
            string alertType = ViewData["Error"] != null ? "danger" : "success";
            string alertIcon = ViewData["Error"] != null ? "fa-exclamation-circle" : "fa-check-circle";
            string alertHeading = ViewData["Error"] != null ? "Error!" : "Success!";
            string alertMessage = ViewData["Error"] != null ? ViewData["Error"].ToString() : ViewData["Message"].ToString();
            <div class="alert alert-@alertType alert-dismissible fade show" role="alert" id="dynamic-alert">
                <!-- Add cancel button with icon at the top -->
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="d-flex align-items-center">
                    <i class="fa @alertIcon me-2"></i>
                    <div>
                        <h5 class="alert-heading">@alertHeading</h5>
                        <p id="alert-message">@alertMessage</p>
                    </div>
                </div>
            </div>
        }
    }

</div>
@if (TempData.ContainsKey("ResultMessage"))
{
    <div class="alert @((TempData["ResultMessage"].ToString().StartsWith("Success")) ? "alert-success" : "alert-danger")">
        @TempData["ResultMessage"]
    </div>
}
<button type="button" class="btn btn-primary" style="background-color: #25237a;">
    <a asp-action="CreateBrokerInsuranceSubType" style="color: white; text-decoration: none;">Create New</a>
</button>
<input type="text" id="searchTerm" placeholder="Search by name...">
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Broker)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InsuranceType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PercentageToBank)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Comment)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InsuranceType.Broker.BrokerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InsuranceType.InsuranceType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PercentageToBank)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Comment)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <button type="button" class="btn btn-sm btn-primary" style="background-color: #25237a; display: inline-block;">
                        <a asp-action="EditBrokerInsuranceSubType" asp-route-id="@item.Id" style="color: white; text-decoration: none;"><i class="zmdi zmdi-edit"></i></a>
                    </button>

                    <button type="button" class="btn btn-sm btn-danger" style="background-color: #f00; border-color: #f00; display: inline-block;">
                        <a asp-action="DeleteBrokerInsuranceSub" asp-route-id="@item.Id" style="color: white; text-decoration: none;"><i class="zmdi zmdi-delete"></i></a>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="~/assets/bundles/libscripts.bundle.js"></script>
@*<script src="~/assets/bundles/mainscripts.bundle.js"></script>*@
<script src="~/assets/bundles/vendorscripts.bundle.js"></script>

<script>
    const searchInput = document.getElementById('searchTerm');

    searchInput.addEventListener('keyup', (e) => {
        if (e.key === "Enter") {
            searchByName();
        }
    });

    function searchByName() {
        const searchTerm = searchInput.value.trim().toLowerCase();
        const rows = document.querySelectorAll('tbody tr');

        rows.forEach(row => {
            const accountNameCell = row.getAttribute('data-account-name').toLowerCase();

            if (!accountNameCell.includes(searchTerm)) {
                row.style.display = 'none';
            } else {
                row.style.display = '';
            }
        });

        // Show "No results" if needed
        showNoResultsMessage();
    }

    function showNoResultsMessage() {
        const visibleRows = document.querySelectorAll('tbody tr:not([style*="display: none"])');

        if (visibleRows.length === 0) {
            // Show no results message or take appropriate action
        } else {
            // Hide no results message or take appropriate action
        }
    }

    // Initially filter on page load
    searchByName();
</script>

InsuranceManagement/Views/Broker/CreateBroker.cshtml
@model InsuranceCore.Models.Broker
@{
    ViewData["Title"] = "CreateBroker";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2 style="text-align: center;">Create Broker</h2>

<!-- Form for creating a new Broker -->
<form asp-action="CreateBroker" method="post">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <strong>
            <label asp-for="AccountNumber" class="control-label"></label>
            <input id="AccountNumber" asp-for="AccountNumber" class="form-control" onblur="fetchAccountDetails()" />

            <span asp-validation-for="AccountNumber" class="text-danger"></span>
        </strong>

    </div>
    <div class="form-group">
        <label asp-for="BrokerName" class="control-label">Broker Name:</label>
        <input asp-for="BrokerName" class="form-control" />
        <span asp-validation-for="BrokerName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="AccountName" class="control-label">Account Name:</label>
        <input asp-for="AccountName" class="form-control" readonly />
        <span asp-validation-for="AccountName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Status" class="control-label">Status:</label>
        <select asp-for="Status" class="form-control" required>
            <option value="">-- Select Status --</option>
            <option value="Active">Active</option>
            <option value="Inactive">Inactive</option>
        </select>
        <span asp-validation-for="Status" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CustomerID" class="control-label">Customer ID:</label>
        <input asp-for="CustomerID" class="form-control" readonly />
        <span asp-validation-for="CustomerID" class="text-danger"></span>
    </div>



    <div class="form-group">
        <label asp-for="EmailAddress" class="control-label">Email Address:</label>
        <input asp-for="EmailAddress" class="form-control" readonly />
        <span asp-validation-for="EmailAddress" class="text-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary" style="background-color: #25237a;">Create Broker</button>
</form>

<!-- Display fetched data (if available) -->
@if (Model != null)
{
    <div class="card mt-4">
        <div class="card-body">
            <h4 class="card-title">Fetched Data</h4>
            <dl class="row">
                <dt class="col-sm-3">Account Name:</dt>
                <dd class="col-sm-9">@Model.AccountName</dd>

                <dt class="col-sm-3">Customer ID:</dt>
                <dd class="col-sm-9">@Model.CustomerID</dd>

                <dt class="col-sm-3">Customer Email:</dt>
                <dd class="col-sm-9">@Model.EmailAddress</dd>

                <dt class="col-sm-3">Customer Name:</dt>
                <dd class="col-sm-9">@Model.BrokerName</dd>
                <!-- Add other properties as needed -->
            </dl>
        </div>
    </div>
}
<script>
  function fetchAccountDetails() {
    console.log("fetchAccountDetails called");

    var accountNumber = $('#AccountNumber').val();
      console.log("accountNumber: " + accountNumber);
    $.ajax({
        url: '@Url.Action("FetchAccountDetails", "Insurance")',
        type: 'POST',
        data: { accountNumber: accountNumber },
        success: function (response) {
            console.log("AJAX success");
            $('#AccountName').val(response.accountName);
            $('#CustomerName').val(response.customerName);
            $('#CustomerID').val(response.t24CustomerID);
            $('#EmailAddress').val(response.customerEmail);
        }
    });

  }



</script>
<div>
    <a asp-action="Index" class="btn btn-success">Back to List</a>
</div>

InsuranceManagement/Views/Broker/CreateBrokerInsuranceSubType.cshtml
@model InsuranceCore.Models.BrokerSubInsuranceType

@{
    ViewData["Title"] = "CreateBrokerInsuranceSubType";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2 style="text-align: center;">Create Broker Insurance SubType</h2>

@*<h4>BrokerSubInsuranceType</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateBrokerInsuranceSubType">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="BrokerId" class="control-label"></label>
                <select asp-for="BrokerId" class="form-control" asp-items="ViewBag.BrokerId" id="BrokerId" required>
                    <option value="">-- Select Broker --</option>
                </select>
            </div>

            <div class="form-group">
                <label asp-for="BrokerInsuranceTypeId" class="control-label"></label>
                <select asp-for="BrokerInsuranceTypeId" class="form-control" asp-items="ViewBag.BrokerInsuranceTypeId" id="BrokerInsuranceTypeId" required>
                    <option value="">-- Select Broker Insurance Type --</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                @*<input asp-for="Name" class="form-control" required />
        <span asp-validation-for="Name" class="text-danger"></span>*@
                <select asp-for="Name" class="form-control" asp-items="ViewBag.BrokerInsuranceSubTypeId" id="BrokerInsuranceSubTypeId" required>
                    <option value="">-- Select Broker Insurance Type --</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="PercentageToBank" class="control-label"></label>
                <input asp-for="PercentageToBank" class="form-control" required />
                <span asp-validation-for="PercentageToBank" class="text-danger"></span>
            </div>
            @Html.HiddenFor(model => model.Comment)

            @*<div class="form-group">
            <label asp-for="Comment" class="control-label"></label>
            <input asp-for="Comment" class="form-control" />
            <span asp-validation-for="Comment" class="text-danger"></span>
        </div>*@

            <div class="form-group">
                <label asp-for="Status" class="control-label">Status:</label>
                <select asp-for="Status" class="form-control" required>
                    <option value="">-- Select Status --</option>
                    <option value="Active">Active</option>
                    <option value="Inactive">Inactive</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary btn-default lgtime" style="background-color: #25237a;" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="BrokerInsuranceSubTypeIndex" class="btn btn-success">Back to List</a>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/nouislider@14.6.0/distribute/nouislider.min.js"></script>

<script>
    $('#BrokerId').change(function () {
        var selectedBrokerId = $(this).val();
        console.log('Selected Broker ID: ' + selectedBrokerId); // Log selected Broker ID
        // Make an AJAX call to fetch and populate Insurance Types based on selected Broker
        $.get('/Insurance/GetInsuranceTypes', { brokerId: selectedBrokerId }, function (data) {
            $('#BrokerInsuranceTypeId').empty(); // Clear previous options
            $('#BrokerInsuranceTypeId').append($('<option>', { value: '', text: '-- Select Broker Insurance Type --' }));
            $.each(data, function (index, item) {
                $('#BrokerInsuranceTypeId').append($('<option>', { value: item.value, text: item.text }));
            });
            console.log('Broker InsuranceType Types loaded.'); // Log when Insurance Types are loaded
        });
    });

    $('#BrokerInsuranceTypeId').change(function () {
        var selectedInsuranceTypeId = $(this).val();
        console.log('Selected Insurance Type ID: ' + selectedInsuranceTypeId); // Log selected Insurance Type ID
        // Make an AJAX call to fetch and populate Insurance Sub Types based on selected Insurance Type
        $.get('/Broker/GetInsuranceSubTypes', { insuranceTypeId: selectedInsuranceTypeId }, function (data) {
            $('#BrokerInsuranceSubTypeId').empty(); // Clear previous options
            $('#BrokerInsuranceSubTypeId').append($('<option>', { value: '', text: '-- Select Broker Insurance Sub Type --' }));
            $.each(data, function (index, item) {
                $('#BrokerInsuranceSubTypeId').append($('<option>', { value: item.value, text: item.text }));
            });
            console.log('Insurance Sub Types loaded.'); // Log when Insurance Sub Types are loaded
        });
    });

</script>

InsuranceManagement/Views/Broker/DeleteBroker.cshtml
@model InsuranceCore.Models.Broker

@{
    ViewData["Title"] = "DeleteBroker";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2 style="text-align: center;">DeleteBroker</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Broker</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BrokerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BrokerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AccountName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccountName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AccountNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccountNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
    </dl>
    
    <form asp-action="DeleteBroker">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <<div>
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>

    </form>
</div>